### ISSUE TITLE
More Permissive License

### ISSUE THREAD

**Issue by skwashd** [govcms-training/content-admin#2]
This project is licensed licensed under the CC-BY-NC-ND. This prevents anyone making changes to tailor the material for a different audience or even creaking a fork to fix a problem. Further the non commercial license prevents people delivering commercial training using this material.

I discussed this with Sharyn and the govCMS team at DrupalSouth. It seems that the license doesn't match the intention. I propose that you use the CC-BY-SA license that encourages people to use the material and contribute changes back to the project. This way govCMS and Digital Salsa get credit for their work, but others can use this great resource.

**Comment by simesy** [comment]
Strong agreement

**Comment by murraywoodman** [comment]
Yes, I agree as well. The materials cannot be adapted for individual sites or used by other providers in a commercial context. As it stands they are useful for people needing instruction for an out of the box installation but nothing else.

**Comment by nathan-w** [comment]
We will discuss this with Salsa Digital with a view to adopting a better licence. @skwashd is correct, it doesn't match the intention, so there's a need to tweak this.

**Comment by kristydv** [comment]
Thanks for raising this @skwashd - the license has been updated in the LICENSE file, the README.md file and in the docx and PDF files. I'll close this ticket for now, but reopen if there any further comments.
