### ISSUE TITLE
Split out lessons/exercises in non-proprietary format

### ISSUE THREAD

**Issue by simesy** [govcms-training/content-admin#3]
The format of this repository does not reflect the spirit of open source. It's not conducive to collaboration by the govcms community through PRs and so forth. I would suggest:

- select a static site generator suitable for training sites
- move everything into plain text eg markdown
- split out lessons into subfolders with exercises further separated
- provide a roadmap for new lessons and video material go with the lessons

**Comment by kristydv** [comment]
I have split out your four suggestions in to their own issue, and added them to the "Format Enhancement" milestone: https://github.com/govcms-training/content-admin/milestone/1

**Comment by kristydv** [comment]
- Select a static site generator suitable for training sites
  - Gitbook has been selected and completed in https://github.com/govcms-training/content-admin/issues/4  

- Move everything into plain text eg markdown:
  -  Completed in https://github.com/govcms-training/content-admin/issues/8

- Split out lessons into subfolders with exercises further separated
  - Added to https://github.com/govcms-training/content-admin/issues/6

- provide a roadmap for new lessons and video material go with the lessons
  - Added to https://github.com/govcms-training/content-admin/issues/7 and there's also the [GovCMS-Training Roadmap](https://github.com/orgs/govcms-training/projects/1)
