### ISSUE TITLE
Select a static site generator suitable for training sites

### ISSUE THREAD

**Issue by kristydv** [govcms-training/content-admin#4]
The current format of the training manuals are as docx and PDF. In order to improve the process for using and learning from these modules, as well as for ease of use for contributing to the training manuals in the future, @simesy had the suggestion to select a static site generator for training sites. 

Look in to options for a static site generator, perhaps 
- https://readthedocs.org or
- https://docusaurus.io/

**Comment by tobybellwood** [comment]
Nice overview of options at https://dev.to/fuad/5-free-static-documentation-generators-you-must-check-out-5ged

**Comment by kristydv** [comment]
https://gitbook.com has been chosen for now.
